### PR TITLE
Install Activiti using Salt

### PR DESCRIPTION
**Pull request by pkimber**
https://www.kbsoftware.co.uk/crm/ticket/1945/

### CODE REVIEW

**Comment by pkimber** [comment]
Do you mean 1024m is too high?  I did try 512m and I kept getting out of memory errors.
We have now removed `activiti-app`, so perhaps 512m will work?

**Comment by mdinsmore** [comment]
Yes, I was thinking as the activiti app war is twice the size of the
activiti-rest war so presumably it will need less memory by only have one
webapp.

Interestingly Activiti runs fine on my laptop with the default setting of
JAVA_OPTS="-Djava.awt.headless=true -Xmx128m -XX:+UseConcMarkSweepGC" for
tomcat 8.  Though that is using the h2 database rather than postgresql.

Malcolm

**Comment by pkimber** [comment]
Hi @mdinsmore 
I did that change, but it seems to have killed the server.  I can only get the site working by re-starting uwsgi, but it all stops working once I access Activiti.
I will investigate further later...
Pat

**Comment by pkimber** [comment]
Hi @mdinsmore 
It is all working again now.
Are you happy to merge this pull request?
Thank you,
Pat

**Comment by mdinsmore** [comment]
Ok I'll reply to this one...  Glad you got it working without my
suggestions!

I've merged

Do you know why it was not working after you made the change?

Malcolm

**Comment by pkimber** [comment]
@mdinsmore  I am confused.  I did everything you suggested (unless I missed something).
I don't know why it suddenly started working.  In my mind, it is because Tomcat takes a very long time to extract the massive `war` file.
I can probably reproduce the issue if you want to look at it.

**Comment by mdinsmore** [comment]
You're right to be confused, I didn't explain myself well - I was replying
to your email (where you'd said it was not working) with some suggestions
when I noticed the new email where you said it was now working - it all
made sense in my head!!

**Comment by pkimber** [comment]
@mdinsmore Thank you for your help.  Your suggestions worked, thank you.

**Pull request merged**
